name: build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - 'master'
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      -
        name: Verify required files
        run: |
          if (!(Test-Path "main.go")) { Write-Error "main.go not found"; exit 1 }
          if (!(Test-Path "go.mod")) { Write-Error "go.mod not found"; exit 1 }
          if (!(Test-Path "versioninfo.json")) { Write-Error "versioninfo.json not found"; exit 1 }
          if (!(Test-Path "res/papp.ico")) { Write-Error "res/papp.ico not found"; exit 1 }
          if (!(Test-Path "res/papp.manifest")) { Write-Error "res/papp.manifest not found"; exit 1 }
          Write-Host "All required files found"
      -
        name: Build application
        run: |
          go mod download
          go mod tidy
          go generate
          go build -ldflags "-s -w" -o vscode-portable.exe
          Write-Host "Build completed successfully"
      -
        name: Download VSCode
        shell: powershell
        run: |
          $version = "1.101"
          $url = "https://update.code.visualstudio.com/$version/win32-x64-archive/stable"
          Write-Host "Downloading VSCode $version from: $url"
          
          # Create temp directory
          New-Item -ItemType Directory -Path "temp" -Force
          
          # Download with retry logic
          $maxRetries = 3
          $retryCount = 0
          do {
            try {
              Invoke-WebRequest -Uri $url -OutFile "temp/vscode.zip" -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
              Write-Host "Download completed"
              break
            } catch {
              $retryCount++
              Write-Host "Download failed, retry $retryCount/$maxRetries"
              if ($retryCount -ge $maxRetries) { throw }
              Start-Sleep -Seconds 5
            }
          } while ($retryCount -lt $maxRetries)
          
          # Extract
          Write-Host "Extracting VSCode..."
          Expand-Archive -Path "temp/vscode.zip" -DestinationPath "temp/vscode-extracted" -Force
          
          # Move to app directory
          New-Item -ItemType Directory -Path "app" -Force
          Move-Item "temp/vscode-extracted/*" "app/" -Force
          
          # Verify extraction
          if (!(Test-Path "app/Code.exe")) { 
            Write-Error "VSCode extraction failed - Code.exe not found"
            exit 1 
          }
          Write-Host "VSCode extracted successfully"
      -
        name: Create portable structure
        shell: powershell
        run: |
          Write-Host "Creating portable structure..."
          
          # Create portable directory structure
          New-Item -ItemType Directory -Path "vscode-portable" -Force
          New-Item -ItemType Directory -Path "vscode-portable/app" -Force
          New-Item -ItemType Directory -Path "vscode-portable/data" -Force
          New-Item -ItemType Directory -Path "vscode-portable/data/appdata" -Force
          New-Item -ItemType Directory -Path "vscode-portable/data/extensions" -Force
          New-Item -ItemType Directory -Path "vscode-portable/data/logs" -Force
          
          # Copy VSCode files
          Write-Host "Copying VSCode files..."
          Copy-Item -Path "app/*" -Destination "vscode-portable/app/" -Recurse -Force
          
          # Copy launcher
          Copy-Item -Path "vscode-portable.exe" -Destination "vscode-portable/"
          
          # Copy code.cmd if exists
          if (Test-Path "res/code.cmd") {
            Copy-Item -Path "res/code.cmd" -Destination "vscode-portable/"
          }
          
          # Create README for users using here-string with single quotes
          @'
# VSCode Portable 1.101-50

## Usage
1. Run vscode-portable.exe to start Visual Studio Code
2. All your settings and extensions will be saved in the data folder
3. Use code.cmd for command-line access (if available)

## What's New in VSCode 1.101
- Enhanced AI capabilities with MCP support
- Improved Copilot integration
- Better multi-window support
- Enhanced debugging tools

Built by: hungvminh
Source: https://github.com/hungvminh/vscode-portable
'@ | Out-File -FilePath "vscode-portable/README.txt" -Encoding UTF8
          
          # Create archive
          Write-Host "Creating archive..."
          Compress-Archive -Path "vscode-portable/*" -DestinationPath "vscode-portable-1.101-50-win64.zip" -Force
          
          # Verify archive
          if (!(Test-Path "vscode-portable-1.101-50-win64.zip")) {
            Write-Error "Archive creation failed"
            exit 1
          }
          
          $archiveSize = (Get-Item "vscode-portable-1.101-50-win64.zip").Length / 1MB
          Write-Host "Archive created successfully ($([math]::Round($archiveSize, 2)) MB)"
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-portable-1.101-50-win64
          path: |
            vscode-portable-1.101-50-win64.zip
            vscode-portable.exe
          retention-days: 30
      -
        name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vscode-portable-1.101-50-win64.zip
            vscode-portable.exe
          body: |
            # VSCode Portable 1.101-50
            
            Portable version of Visual Studio Code 1.101 with latest AI features.
            
            ## Features
            - VSCode 1.101 with MCP support
            - Completely portable - no installation required
            - All data stored in portable directory
            - Windows 64-bit support
            
            ## Download
            - **vscode-portable-1.101-50-win64.zip** - Complete portable package
            - **vscode-portable.exe** - Launcher executable only
            
            ## Installation
            1. Download the ZIP file
            2. Extract to your preferred location
            3. Run vscode-portable.exe
            
            Built by: hungvminh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}