name: released

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Release notification
        run: |
          echo "Release ${{ github.event.release.tag_name }} has been published!"
          echo "Download URL: ${{ github.event.release.html_url }}"